CREATE SEQUENCE  "SYSTEM"."SEQ_IDPASAJERO"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE TABLE SYSTEM.PASAJERO
(
    PASAJERO_ID NUMBER(10,0) DEFAULT SEQ_IDPASAJERO.NEXTVAL PRIMARY KEY,
    PRIMERNOMBRE VARCHAR2(50) NOT NULL,
    SEGUNDONOMBRE VARCHAR2(50) NULL,
    PRIMERAPELLIDO VARCHAR2(50) NOT NULL,
    SEGUNDOAPELLIDO VARCHAR2(50) NULL,
    TIPO_DOCUMENTO VARCHAR2(100) NOT NULL,
    NUM_DOCUMENTO VARCHAR2(20) NOT NULL,
    FECHANACIMIENTO DATE NOT NULL,
    PAIS VARCHAR2(100) NOT NULL,
    TELEFONO NUMBER(8, 0) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    CLAVE VARCHAR(50) NOT NULL,
    ACTIVO NUMBER(1, 0) DEFAULT 1
)